# Generated by Django 5.2.4 on 2025-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='color_tag',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('red', 'Red')], default='yellow', max_length=20),
        ),
    ]
